const NODE_ENV = process.env.NODE_ENV;
const PORT = process.env.PORT;
const MONGO_URL = process.env.MONGO_URL;
const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET;

const DATABASE_NAME = 'learning_management_system';
const ORIGIN_URL = process.env.ORIGIN_URL;

const POSTMAN_URL = process.env.POSTMAN_URL;

const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
const CLOUDINARY_API_SECRET_KEY = process.env.CLOUDINARY_API_SECRET_KEY;

const STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY;
const STRIPE_PUBLISHABLE_KEY = process.env.STRIPE_PUBLISHABLE_KEY;
const WEBHOOK_ENDPOINT_SECRET = process.env.WEBHOOK_ENDPOINT_SECRET;

export {
	NODE_ENV,
	PORT,
	MONGO_URL,
	ACCESS_TOKEN_SECRET,
	DATABASE_NAME,
	ORIGIN_URL,
	POSTMAN_URL,
	CLOUDINARY_CLOUD_NAME,
	CLOUDINARY_API_KEY,
	CLOUDINARY_API_SECRET_KEY,
	STRIPE_SECRET_KEY,
	STRIPE_PUBLISHABLE_KEY,
	WEBHOOK_ENDPOINT_SECRET,
};
